<a href="https://colab.research.google.com/github/obarreto/Python/blob/main/Aula_2_matrizes_especiais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
matriz.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [3]:
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Matriz Inversa

A matriz inversa é uma matriz que e obtida a partir de uma matriz quadrada A, tal que o produto entre ela e sua inversa resulta na matriz indentidade. A inversa de uma matriz A é denotada por A^-1. Para calcular a matriz inversa de uma matriz A, é necessário que o determinante de A seja diferente de zero. A representação matemática da matriz inversa de matriz A é

A matriz inversa tem alguma propriedades interessantes, como:

A inversa da inversa de uma matriz é igual à matriz original:
(A¬¹)-¹ = A

A inversa da matriz identidade é igual à matriz identidade:
I-¹ = I

A inversa da soma de duas matrizes é igual à soma das inversas de cada matriz:
(A + B)-¹ = A-¹ + B-¹

In [ ]:
A = matriz
A

In [ ]:
# Para a matriz A ter matriz inversa.
# matriz original tem que ser quadrada : 4x4
# determinante da original tem que ser diferente de zero

# determinante de A tem que ser diferente de zero
np.linalg.det(A) #linalg() - Linged Alg / Algebra Linear

In [ ]:
# calculando a inversa da matriz A

np.lingalg.inv(A)

In [ ]:
A_inv = np.linalg.inv(A) # matriz inversa


In [ ]:
A

In [ ]:
A_inv